server:
  port: 8001
spring:
  application:
    name: eureka
#  security:
#    user:
#      name: wkt
#      password: wkt123456
eureka:
  instance:
   hostname: 127.0.0.1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka
