server:
  port: 8002
spring:
  application:
    name: consumer
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka
      instance:
        lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
        lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
        prefer-ip-address: true
        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}:${server.port}
swagger:
  print-init: true
  enabled: true
  docket:
    base-package: com.study.consumer.web
    api-info:
      contact:
        email: 1825793811@qq.com
        name: Kt.w
        url:  https://github.com/kaitongwang
      title: Study  spring cloud 学习计划

      version: 1.1.0
      description: Api接口文档
    host: 127.0.0.1
    path-mapping: /

feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    polling-interval-ms: 6000