server:
  port: 8005
spring:
  application:
    name: jedis
  redis:
    host: www.wkt.red
    port: 6379
    password: love54542946
    timeout: 2000
    database: 0  # 数据库
    jedis:
      pool:
        max-active: 50  # 最大连接数
        max-wait: 3000   # 连接超时间
        max-idle: 20    # 最大连接空闲数
        min-idle: 10   # 最小连接空闲数
  mail:
    host: smtp.qq.com
    username: 1825793811@qq.com
    password: aaruournfvllegff
    default-encoding: utf-8



eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka
      instance:
        lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
        lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
        prefer-ip-address: true
        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}:${server.port}



swagger:
  print-init: true
  enabled: true
  docket:
    base-package: com.study.jedis.web
    api-info:
      contact:
        email: 1825793811@qq.com
        name: Kt.w
        url:  https://github.com/kaitongwang
      title: 基础数据api
      version: 1.1.0
      description: Api 文档
    host: 127.0.0.1
    path-mapping: /

#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com:
      htlb:
        log:
          mapper: debug
  file: /root/logs/jedis/output.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

